[theme]
primaryColor = "#0079eb"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#ffffff"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = true
headless = true
port = 8501

[browser]
gatherUsageStats = false
